### ISSUE TITLE
Load data over https

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-plugin-gmap#8]
@sweety-wo The plugin should load data over https.
Mixed Content: The page at 'https://54.67.43.161/#/dynamic-page/097a6b8a' was loaded over HTTPS, but requested an insecure script 'http://maps.googleapis.com/maps/api/js?v=3.22&region=US'. This request has been blocked; the content must be served over HTTPS.

**Comment by sweety-wo** [comment]
I have set  HTTPS for google apis. 
So,now URL is **'https://maps.googleapis.com/maps/api/js?v=3.22&region=US'**.

Please check it.

**Comment by sweety-wo** [comment]
Hello,

I have send pull request with fixed #7 and #8 issues.

I have set HTTPS for google apis.
So,now URL is 'https://maps.googleapis.com/maps/api/js?v=3.22&region=US'.

I have attached latest plugin file.

Please check it.

Thank you.
